- name: Playbook for basic configuration
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Installing additional packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - neofetch
        - htop
      become: true  

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Start Nginx
      service:
        name: nginx
        state: started
      become: true

    - name: Copy index.html
      copy:
        src: /home/user/code/NGINX/index.html
        dest: /var/www/html/index.html
      become: true

    - name: Copy nginx.conf
      copy:
        src: /home/user/code/NGINX/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: true

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: true

    - name: Check Nginx status
      shell: systemctl status nginx
      register: result
      become: true

    - name: Print Nginx status
      debug:
        var: result.stdout_lines
      become: true